Miller Rabin test bases on the following fact for a prime p: 
	for all numbers 1 <= a < p: 
		a^(p-1) = 1 (mod p)
		
Since you do not want to test all a < p to be sure that p is prime and not pseudo prime,
it was shown that it is sufficient to test all a <= 2 * log(n)^2.
Moreover, for p < 318.665.857.834.031.151.167.461 it was shown that a <= 37 is enough
(See: https://de.wikipedia.org/wiki/Miller-Rabin-Test)